spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
  data:
    mongodb:
      database: library

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework8.mongock.changelog
