spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
  data:
    mongodb:
      database: books
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework14.mongock.changelog
