spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: /db/changelog/changelog.yaml
  h2:
    console:
      enabled: true
#  sql:
#    init:
#      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    ROOT: INFO